modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="GNU General Public License v3.0" #mandatory
issueTrackerURL="https://github.com/ToMe25/TriGems/issues"
[[mods]] #mandatory
    modId="trigems" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="TriGems" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/trigems"
    credits=""
    authors="ToMe25"
    description='''A simple Mod wich adds Three Gems with armor and Tool sets, a Emerald armor set and a Emerald Tool set.'''
[[dependencies.tomesetup]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tomesetup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
